=== VIVEKANAND-SINHA/HTMl-and-CSS/food.dtd
<!DOCTYPE food [ 
<!ELEMENT food (fruits)*> 
<!ELEMENT fruits (name, color, taste)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT taste (#PCDATA)>
]>

=== VIVEKANAND-SINHA/HTMl-and-CSS/intro.xml
<?xml version="1.0" encoding="UTF-8"  standalone='no'?>
<!DOCTYPE food SYSTEM "food.dtd">
<food>
    <fruits >
        <name> apple </name>
        <color> red </color>
        <taste> sweet </taste>
    </fruits>
    <fruits >
        <name> Mango </name>
        <color> Yellow </color>
        <taste> sweet </taste>
    </fruits>
    <fruits >
        <name> Banana </name>
        <color> Yellow </color>
        <taste> sweet </taste>
    </fruits>
    <fruits >
        <name> Mango </name>
        <color> Yellow </color>
        <taste> sweet </taste>
    </fruits>
    <fruits>
        <name> watermelon</name>
        <color> green </color>
        <taste> sweet </taste>
    </fruits>
</food>
